name: Galaxy Tool Linting and Tests for push and PR
on: [push, pull_request]
env:
  GALAXY_REPO: https://github.com/galaxyproject/galaxy
  GALAXY_RELEASE: release_20.05
jobs:
  setup:
    name: Setup cache and determine changed repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
    - name: Print github context properties
      run: |
        echo 'event: ${{ github.event_name }}'
        echo 'sha: ${{ github.sha }}'
        echo 'ref: ${{ github.ref }}'
        echo 'head_ref: ${{ github.head_ref }}'
        echo 'base_ref: ${{ github.base_ref }}'
        echo 'event.before: ${{ github.event.before }}'
        echo 'event.after: ${{ github.event.after }}'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_${{ matrix.python-version }}_${{ env.GALAXY_RELEASE }}
    - name: Cache tool_cache
      uses: actions/cache@v2
      id: cache-tool-cache
      with:
        path: ~/tool_cache
        key: tool_cache_${{ env.GALAXY_RELEASE }}
    - name: Setup cmvfs
      run: ./.scripts/setup_cvmfs.sh
    - run: pip install https://github.com/jmchilton/planemo/archive/rework_workflow_staging.zip
    - run: sed "s|/cvmfs/main.galaxyproject.org/shed_tools|$HOME/cvmfs/main/shed_tools\" tool_cache_data_dir=\"$HOME/tool_cache|g" ~/cvmfs/main/config/shed_tool_conf.xml > ~/shed_tool_conf.xml
    - run: sed "s|/cvmfs/data.galaxyproject.org|$HOME/cvmfs/data|g" ~/cvmfs/data/managed/location/tool_data_table_conf.xml > ~/tool_data_table_conf_managed.xml
    - run: sed "s|/cvmfs/data.galaxyproject.org|$HOME/cvmfs/data|g" ~/cvmfs/data/byhand/location/tool_data_table_conf.xml > ~/tool_data_table_conf_by_hand.xml
    - run: echo 'how does this work'
    - run: planemo test --database_connection postgresql://postgres:postgres@localhost:5432/galaxy --no_conda_auto_init --no_dependency_resolution --biocontainers --shed_tool_conf ~/shed_tool_conf.xml --no_shed_install --tool_data_table ~/tool_data_table_conf_by_hand.xml --tool_data_table ~/tool_data_table_conf_managed.xml --docker_extra_volume ~/cvmfs/data workflows/sars-cov-2-variant-calling/workflow.ga || true
    - name: Copy artifacts into place
      run: |
        mkdir upload
        mv tool_test_output.json tool_test_output.html upload/
    - uses: actions/upload-artifact@v2.0.1
      with:
        name: 'Workflow test report'
        path: upload
